sonar.projectKey=sindri
sonar.projectName=Sindri
sonar.projectVersion=1.0

sonar.sources=backend/app,frontend/src
sonar.exclusions=**/node_modules/**,**/venv/**,**/dist/**,**/__pycache__/**,**/migrations/**

sonar.python.version=3.13
sonar.host.url=http://localhost:9000
sonar.token=sqa_42ba5ea1528824e87edfac874b50f4a318156d3c